### ISSUE TITLE
Support UTF-8 characters (e.g. Hebrew)

### ISSUE THREAD

**Issue by orenagiv** [tazatechnology/openapi_spec#43]
Hey,
While using the [LangChain.dart package](https://pub.dev/packages/langchain), which uses the `openapi_spec` package, I've noticed that if the OpenAI response includes characters in Hebrew or other languages with special characters - it results with "gibberish".

This is most probably due to `client.dart` > lines 883 and 896, where `json.decode` is done `over r.body`:
https://github.com/search?q=repo%3Atazatechnology%2Fopenapi_spec+json.decode%28r.body%29&type=code

It seems that due to this Dart issue:
https://github.com/dart-lang/http/issues/789

The `json.decode` should be done with `utf8.decode` over the `r.bodyBytes`, in order to properly handle the UTF-8 chars:
```
if (s.ref != null || returnType.startsWith('Union')) {
  decoder = "return $returnType.fromJson(json.decode(utf8.decode(r.bodyBytes)));";
} else {
  decoder = """
    final list = json.decode(utf8.decode(r.bodyBytes)) as List;
    return list.map((e) => ${s.items.ref}.fromJson(e)).toList();
```
 
I've manually manipulated the generated `client.dart` file - and it resolved the problem.
However, unfortunately, due to lack of time I'm unable to test this properly and submit a Pull Request...
I hope the maintainers will have to take a look soon.

**Comment by walsha2** [comment]
Looks like there is some confusion in the `http` package about the expected/default decode logic. I assumed that `utf-8` was the default, but I suppose that is not the case.

@orenagiv this has been taken care of in #44 and successfully published to [`openapi_spec` (v0.7.8)](https://pub.dev/packages/openapi_spec). @davidmigloz should be able to integrate in to  LangChain Dart soon.

**Comment by davidmigloz** [comment]
Fixed in:
- [`openai_dart: 0.1.1+2`](https://pub.dev/packages/openai_dart/changelog#0112)
- [`langchain_openai 0.1.2+1 `](https://pub.dev/packages/langchain_openai/changelog#0121)

Thank you both!

**Comment by davidmigloz** [comment]
@walsha2 we need to recreate the other clients as well (`pinecone` on your side and `chromadb` on my side).

**Comment by davidmigloz** [comment]
`chromadb` recreated in:
- [`chromadb: 0.1.0+2`](https://pub.dev/packages/chromadb/changelog#0102)
- [`langchain_chroma: 0.1.0+5 `](https://pub.dev/packages/langchain_chroma/changelog#0105)

**Comment by orenagiv** [comment]
**Thanks** @davidmigloz @walsha2 !
**Works great! 👍**

**Comment by walsha2** [comment]
> @walsha2 we need to recreate the other clients as well (`pinecone` on your side and `chromadb` on my side).

- [`pinecone: 0.7.2`](https://pub.dev/packages/pinecone)
