### ISSUE TITLE
Request returns void when response body is empty

### ISSUE THREAD

**Issue by mthongvanh** [tazatechnology/openapi_spec#47]
When the path entry returns only a status code the generated request returns void. 

I think it would be better to return a response object, because I think most users will expect a success response. If they forget to wrap in a try-catch they might miss errors.

Considering the current implementation, I am not sure if this is feasible or not.

One option would be to have the custom response object implement BaseResponse and pass the http library's response into the custom class' constructor. 

If you think this is a worthwhile enhancement, I would happy to take a look.

Here's an example with only a status code:

 ```
 /copy:
    post:
      tags:
      - model management
      summary: Copy a Model
      description: Copy a model. Creates a model with another name from an existing model.
      operationId: copyModel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CopyRequest'
      responses:
        '200':
          description: OK
```

**Comment by davidmigloz** [comment]
I think the client should basically abstract all the HTTP-related stuff. So, in this case, I believe it is correct to return just `void`. Same as if you call `list.add('item')` in dart, it will return `void` or throw an exception if the list is unmodifiable.

**Comment by mthongvanh** [comment]
i can see where you are coming from in terms of the client and trying to keep it similar to other dart APIs. also, i agree that a result wrapper would be nicer, so i think that's why i find it strange not to propagate the empty 200 response.

**Comment by mthongvanh** [comment]
> What is the end user going to do with a propagated 200 response with no content? Is there a practical use case?
Just to verify that the operation did indeed complete as expected, but I think that the `onResponse` would cover that use case.

Understanding the project a little better, I can see how the change doesn't really fit. Thanks for clarifying!
